spring:
  datasource:
    url: jdbc:mysql://150.158.143.246:3306/test01?useSSL=false&serverTimezone=UTC
    username: root
    password: llj199949
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
